'use strict';

/**
 * Who talks to whom (branding/DESIGN.md 7.22): the graph's header card and
 * legend float over the canvas, so the layout keeps every node in the band
 * between them. Generated by /ship coverage audit (pass 1).
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const loadTs = require('./load-ts.cjs');

const { forceLayout } = loadTs('src/renderer/src/components/memoryGraph/forceLayout.ts');

const nodes = Array.from({ length: 30 }, (_, i) => ({ id: `n${i}`, gravityBias: i === 0 ? 2.4 : 1 }));
const edges = nodes.slice(1).map((n) => ({ source: 'n0', target: n.id }));

test('nodes stay clear of the header and legend; a dragged node stays where it was dropped', () => {
  // Value: protects=no person is hidden under the graph's header or legend; fails_when=forceLayout ignores insetTop/insetBottom in the seed, the centre or the clamp, or a short window yields NaN; why_new=forceLayout had no test and the insets are new; seam=none
  const opts = { width: 600, height: 400, padding: 20, insetTop: 80, insetBottom: 60 };
  const pos = forceLayout(nodes, edges, { ...opts, pinned: { n5: { x: 10, y: 5 } } });
  for (const [id, p] of pos) {
    if (id === 'n5') continue;
    assert.ok(p.y >= 100 && p.y <= 320, `${id} at y=${p.y} sits between the header and the legend`);
    assert.ok(p.x >= 20 && p.x <= 580, `${id} at x=${p.x}`);
  }
  assert.deepEqual(pos.get('n5'), { x: 10, y: 5 }, 'a pin is honoured as is');
  // Without insets the same graph uses the full height, so the band above is the insets' doing.
  const plain = [...forceLayout(nodes, edges, { width: 600, height: 400, padding: 20 }).values()];
  assert.ok(plain.some((p) => p.y < 100), 'sanity: the uninset layout reaches into the header band');
  // Deterministic: the same input lays out the same way (no reshuffle between polls).
  assert.deepEqual([...forceLayout(nodes, edges, opts)], [...forceLayout(nodes, edges, opts)]);
  // A window too short for the insets still gives every node a real position.
  const short = forceLayout(nodes, edges, { width: 300, height: 150, padding: 20, insetTop: 80, insetBottom: 60 });
  for (const [id, p] of short) assert.ok(Number.isFinite(p.x) && Number.isFinite(p.y), `${id}: ${JSON.stringify(p)}`);
});

/** Review, 2026-10-01: insets taller than the canvas put every node on one line. */
test('a short graph keeps its nodes spread vertically', () => {
  const nodes = Array.from({ length: 12 }, (_, i) => ({ id: `n${i}` }));
  const short = forceLayout(nodes, [], { width: 300, height: 180, padding: 44, insetTop: 52, insetBottom: 56 });
  const ys = [...short.values()].map((p) => p.y);
  assert.ok(new Set(ys.map(Math.round)).size > 1, 'not all on one line');
  assert.ok(Math.max(...ys) - Math.min(...ys) > 40, `spread ${Math.max(...ys) - Math.min(...ys)}px`);
});
